### PR TITLE
Added click fix for firefox and safari

### PR DESCRIPTION
**Pull request by nr007**

### CODE REVIEW

**Comment by blivesta** [comment]
Thank you for your contribution! worked on safari?

**Comment by nr007** [comment]
Thank you for your work ;) Yes. I tested it on Safari, Firefox and IE.

**Comment by blivesta** [comment]
Nice!. But effect(ripple) does not work on my safari (OSX 8.0.6). 😭
Do you set the url in href?
``` html
<a href="https://github.com" class="btn btn-primary rippler rippler-default">
  Rippler link
</a>
```

**Comment by nr007** [comment]
Actually i am using Emberjs (tested on windows - Safari 5.1.7) and not defining href explicitly. But anchor get handled with on click event.

**Comment by blivesta** [comment]
Ok, This was fixed based on feedback. it work on firefox, safari, IE, chrome.
https://github.com/blivesta/rippler/commit/aab78faefac41cdf8115db06dc583e910459fddb
Can you able to check the work of rippler? Thanks!

**Comment by nr007** [comment]
I found that fix in opened issues. I tried back then and i tried it now again. In Ember it does not work. It makes my view refresh on anchor click.

**Comment by blivesta** [comment]
Can you provide a it's example?

**Pull request merged**
